name: Deploy Hexo to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@v4
#      with:
#        submodules: recursive
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm install
    - run: npx hexo g        # 生成到 public/
    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
